### ISSUE TITLE
Oricutron 1.2 crashes when Telestrat machine selected.

### ISSUE THREAD

**Issue by acepow3r** [pete-gordon/oricutron#109]
What the title says: The Oricutron window closes immediately upon selecting Telestrat under Hardware and pressing "Back" two times.
Don't know how far down it goes, but Oricutron 0.9 seems to work fine with Telestrat.

Host: Windows 8.1 64bit

**Comment by pete-gordon** [comment]
This is fixed already in the repository. The only thing holding up a 1.3 release is that my AmigaOne is currenltly out of action, I don't have time to fix it, and I want to make sure the OS4 build works before I make another release :-(

If someone else volunteered to make sure it still all works on OS4, that would also do.

**Comment by nekoniaow** [comment]
If the issue is fixed should it not be marked as such?
I think GitHub has provisions to indicate that the issue is fixed by a given commit id.

**Comment by jedeoric** [comment]
The problem is, that it's corrected some years ago.

But, there is no release since V1.2, users which does not compile Oricutron, have the problem. I mean, that we could close the issue, many users still have the problem

**Comment by nekoniaow** [comment]
It does not compile? I guess you mean on Windows?
I compiled Oricutron on macOS yesterday so I am a bit surprised.
I also have a Windows PC so I can try fixing that.

**Comment by polluks** [comment]
See #103
